had to create custom mapper for vacancies - for some reason @Mapper  doesn't work - it thinks expFrom and expTo are LocalDateTime objects, but they are integers, so we get there errors: java.lang.NoSuchMethodError: 'java.time.LocalDateTime kg.attractor.jobsearch.model.Vacancy.getExpFrom()